### PR TITLE
Update gitmodules to use HTTPS URL for http-parser

### PR DESCRIPTION
**Pull request by parazyd**
This commit changes the submodule URL to a secure one.

### CODE REVIEW

**Comment by jonashaag** [comment]
Thanks! What's the advantage of that?

**Comment by parazyd** [comment]
Avoiding MITM when cloning, and also some package managers prefer it, and give noisy warnings otherwise.
There's no downside to this change really.

**Comment by jonashaag** [comment]
I’m not sure if it will break people’s checkouts. Do you know?

**Comment by parazyd** [comment]
It won't break anything. New clones will simply use the https URI, and old checkouts which use the git URI are already configured in `.git/modules`, so nothing will change there.

**Comment by parazyd** [comment]
Thanks!

**Pull request merged**
