### PR TITLE
FIx for looping EPIPE issue for unix sockets

### PR DESCRIPTION
**Pull request by supratikchatterjee16**
@jonashaag 

Made modifications to prevent Issue #196 .

Tested for inbuilt TCP stream and unix sockets on Linux only.
Do review the code whenever possible.

### CODE REVIEW

**Comment by ayalster** [comment]
@jonashaag @supratikchatterjee16 
Hi, could you please share if there is a particular reason why this PR was closed and not merged to master?
As far as i can tell the issue #196  still exists and nothing in the current realese address it. Am i missing something?
I do think i encouter it when using version 3.2.2.

**Comment by jonashaag** [comment]
I don’t remember. Does it fix things for you?

**Comment by ayalster** [comment]
Sorry for the late reply - 
It solves a standing issue that i encounter where, when connected via unix sockets, if the client disconnects before reply - it triggers an infinite error loop. I think it may be fixed in a different way in the fixes branch, but i don't know when if / when it is supposed to be merged into a new release version.

**Comment by jonashaag** [comment]
Did you actually try the branch?

**Comment by ayalster** [comment]
Do you mean the fixes branch? no - i preferred to stick with the tried and tested release. and it seemed to have too many changes from master.

**Comment by jonashaag** [comment]
Would be good to know if the fix in this PR actually fixes the problem!

**Comment by ayalster** [comment]
Yes, indeed it solves the issue

**Comment by supratikchatterjee16** [comment]
@jonashaag due to the repository having grown stale by more than a year, I had closed it in order to clean up my own repository. The fix was to implement an unimplemented mechanism that had been coded in.

**Pull request closed without merging**
